### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by budgiegamer** [anIceyGirl/SurvivalOverhaul#13]
Using this mod with a dedicated server leads it to get a server error related to the capabilities upon a player joining

**Comment by budgiegamer** [comment]
Use the Experimental branch as reference to rebuild/deconstruct the stamina system or merge

**Comment by anIceyGirl** [comment]
The latest commit fixes this issue. Turns out it's just the fact that we can't register keybinds in a server, obviously, so i just commented that out for the time being.
