### ISSUE TITLE
[1.16.5] Compatiblity issues or am I missing something?

### ISSUE THREAD

**Issue by Cixon** [anIceyGirl/SurvivalOverhaul#20]
**Mod In Question:** [Gokistats v1.2.13](https://www.curseforge.com/minecraft/mc-mods/gokistats/files/3133823)

**Context:** So I noticed my health isn't recovering at all. Not sure if it was because of the similarity in health modification when it come to the mod I was using (gokistats) in conjunction with SurvivalOverhaul

As you can see, my hunger bar is full but the extra hearts I purchased from the Gokistats skill tree isn't recovering.
![Screenshot (47)](https://user-images.githubusercontent.com/69068153/106712991-63a74e80-65bf-11eb-93b9-23197c68b01c.png)

My skilltree
![Screenshot (49)](https://user-images.githubusercontent.com/69068153/106712997-64d87b80-65bf-11eb-8a53-c276163341d3.png)

**Comment by Cixon** [comment]
Heart Fruits are disabled in my config and I even increased the maximum hearts to 20 in the config for SurvivalOverhaul

**Comment by anIceyGirl** [comment]
I'm not TOTALLY sure what might be going on here, since health regen isn't directly affected by my mod. Try enabling cheats and checking to see if the naturalRegeneration gamerule is true or false.

**Comment by Cixon** [comment]
> 
> 
> I'm not TOTALLY sure what might be going on here, since health regen isn't directly affected by my mod. Try enabling cheats and checking to see if the naturalRegeneration gamerule is true or false.

Gamerule was not set to false. Interesting...

**Comment by Cixon** [comment]
Problem was fixed by utilizing another mod called [HarderNaturalHealing](https://www.curseforge.com/minecraft/mc-mods/harder-natural-healing).

Not sure if this was a ME problem or what...
