### ISSUE TITLE
Foods can add "Warming" or "Cooling" Effect - Suggestion

### ISSUE THREAD

**Issue by ovfudj** [anIceyGirl/SurvivalOverhaul#22]
Allow certain foods to give the player a warming (I,II,III), or cooling (I,II,III) effect with a flat temperature bonus.
This would encourage certain foods and prevent food spam, and could tie into the thirst system described in a different post,
and allow drinking water to apply a cooling I effect for example.

**Comment by anIceyGirl** [comment]
This is already somewhat in the works!
