### ISSUE TITLE
Datapack Causes Crash on Server Load - Create Compatibility

### ISSUE THREAD

**Issue by ovfudj** [anIceyGirl/SurvivalOverhaul#23]
Attempting to load a Create datapack on a server causes it to crash when Create mod is installed with Survival Overhaul.

[logs_latest.log](https://github.com/anIceyGirl/SurvivalOverhaul/files/5928906/logs_latest.log)
[logs_debug.log](https://github.com/anIceyGirl/SurvivalOverhaul/files/5928907/logs_debug.log)

This happens on Survival Overhaul Beta 0.3.1 with Create v0.3e multiplayer only. Tested with no issues on singleplayer when loading datapacks (along with the other mods installed).

**Comment by anIceyGirl** [comment]
This doesn't seem like an issue on our end. Survival Overhaul doesn't touch datapacks at all, so I'm not sure what the deal is with that. Could you send me your modlist?

**Comment by ovfudj** [comment]
Sorry for the confusion I created a dummy server, and found out this is a Create mod only problem. The folks over there told me it was an compatibility issue with your mod after misreading the server logs. There is no compatibility issue so I'm closing this post.
