### ISSUE TITLE
Incompatibility/Crash 

### ISSUE THREAD

**Issue by YejiYeah** [anIceyGirl/SurvivalOverhaul#26]
Hi,

I hope all is well- - - 
I have been trying to include this mod to my modpack but I get this crash always when the weather changes or when I see my armor stats.

Would you please help me?,

Thanks in advnce! 

Best regards,

Sarah X.

[crash-2021-02-17_00.06.21-server.txt](https://github.com/anIceyGirl/SurvivalOverhaul/files/5993616/crash-2021-02-17_00.06.21-server.txt)

**Comment by anIceyGirl** [comment]
I don't think this is a compatibility issue on our end. The first line of the crash log says it's caused by a mod called "Epic Fight." Your best bet would be to take it up with the authors of that mod.
