### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by WenXin20** [anIceyGirl/SurvivalOverhaul#7]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Survival Overhaul v0.1.0-beta`

After joining my server, I crashed client side. It might be related to having Serene Seasons and Better Weather installed, both of which modify weather and temps.
[Crash Report](https://gist.github.com/WenXin20/b3217076cdb6901f6500d3887206794d)

**Comment by anIceyGirl** [comment]
Try removing BetterWeather. I can't promise that this will work, but serene seasons is the primary focus for compatibility, in this case.
